[package]
name = "guessing_game"
version = "0.1.0"
edition = "2024"

[dependencies]
# Cargo understands semantic versioning (aka SemVer)
#     https://semver.org/
# "0.8.5" really means "^0.8.5"
#     (anything at least 0.8.5, but not over 0.9.0)
rand = "0.8.5"
